### PR TITLE
Price displays twice on products with attributes

### PR DESCRIPTION
**Pull request by scottcwilson**
image

### CODE REVIEW

**Comment by lat9** [comment]
I _think_ that @rbarbour had it that way because some sites' products' have a laundry-list of options (like the demo products' Bugs' Life Collectors' Edition).  Let me 'chew' on this a bit.

**Comment by scottcwilson** [comment]
Good point - might be somehow configurable.

**Comment by lat9** [comment]
That's what I was thinking, a "soft" setting in the /extra_datafiles/[dist.]site-specific-bootstrap-settings.php file.

**Comment by lat9** [comment]
Noting, too, that any change is needed for all *5* document/product types' templates.

**Comment by scottcwilson** [comment]
Wonder if we ought to do something like PR #5891 on the storefront side and get rid of these product type specific files unless they are specifically overridden.

**Comment by lat9** [comment]
> Wonder if we ought to do something like PR #5891 on the storefront side and get rid of these product type specific files unless they are specifically overridden.

That PR covered duplicate function handling in the admin only, not the storefront templating, although it would be a "good thing" since the _majority_ of the product-type-specific templates' rendering is common.

**Comment by lat9** [comment]
Closing in deference to issue #285.

**Pull request closed without merging**
