### PR TITLE
Only show price if product is not call for price

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by lat9** [comment]
You need to fix this in the base before I consider the changes for Bootstrap:
image

**Comment by lat9** [comment]
Isn't that change to the observer going to be throwing PHP Warnings, since `$this->product_is_call` isn't set:
https://github.com/lat9/ZCA-Bootstrap-Template/blob/186b4880570745c5d7f87d4a03943fe039b4c89d/includes/classes/observers/ZcaBootstrapObserver.php#L154-L167

... and what's up with that template change?

**Comment by lat9** [comment]
I'm also trying to figure out how the product you're obviously playing with is configured.  Other than the on-sale/is-call-for-price products, I'm not seeing the price included on any of the demo products.

**Comment by scottcwilson** [comment]
Consider a product whose price is generally $100.  But seasonally, it gets harder to find, so they have to make it call for price.  When the season ends, they want it to roll back to $100.  

I think that if the product is call_for_price, the price should simply not be shown. 

> ... and what's up with that template change?
sorry, finger trouble.  Fixed.

**Comment by lat9** [comment]
Since bootstrap is demonstrating the same behavior as the core `responsive_classic` ...

image

... for a 'call for price' product that also has a price, I'm closing this now and will revisit when/if the core changes.

**Pull request closed without merging**
