### PR TITLE
Update product_listing.php

### PR DESCRIPTION
**Pull request by brittainmark**
Efficiency change
Lines 228-288 are process every time, but are not dependent on the value of $col.

I have deliberately not moved the indenting (formatting) so you can see the change. If happy, let me know and I'll correct the formatting.

### CODE REVIEW

**Comment by lat9** [comment]
Looks good; I've opened #188 to track the changes.  Go ahead and move the indentation, indicate that the last change to the module was for v3.5.1 and I'll pull that in!

**Comment by lat9** [comment]
Still need to update the comment on line 5 to read `BOOTSTRAP: v3.5.1`

**Comment by brittainmark** [comment]
Sorry misunderstood. Done now. I have squashed it into the last commit, do you want them squashed to be a single commit?

**Comment by lat9** [comment]
Nope, that's just fine.  Thanks for the update.

**Pull request merged**
