### PR TITLE
Define clearBoth class

### PR DESCRIPTION
**Pull request by scottcwilson**
This class is used in a number of template files, both in bootstrap and template_default, so it needs to be defined.

### CODE REVIEW

**Review by lat9 — COMMENTED** [review]
What is the underlying issue being corrected by this change?

**Comment by scottcwilson** [comment]
- clearBoth is referenced but not defined.
- clearfix is referenced but not defined - but it's a duplicate. 
You can see the impact of not having a clearBoth definition by attempting to use it to clear floats- it won't clear them. 

So if you do a clearboth and then add some text right underneath it (for example), the text will still be floated just like the item before it.

**Comment by scottcwilson** [comment]
Here's a way to dup the issue: If you modify bootstrap's version of tpl_product_info_display.php to add some text right after the clearBoth following Ask a Question, you'll see the text is still floated.

**Comment by lat9** [comment]
There needs to be a way to get that to render properly using clearfix.  One of the tenets of the BootStrap template instituted by Ray Barbour is that the stylesheet.css is kept to a minimum and the Bootstrap classes are maintained.

**Comment by scottcwilson** [comment]
Right now there are 43 references to clearBoth in bootstrap/templates, but this class is not defined so it won't work the way people expect.   You could change all clearBoth classes to clearfix, but then you'd still be in trouble if template_default had a template which was not overridden that referred to clearBoth.    I think my fix is the least intrusive but it's your call.

**Comment by lat9** [comment]
I can see the need for defining the `clearBoth` style, but I'm still not convinced that the associated template changes are required.  I'm open to the change if you can show me something that's not working.

**Comment by scottcwilson** [comment]
Nah, I'll back that out.  So now the PR has just the CSS change.

**Pull request merged**
