### PR TITLE
Improve descriptions of category-tabs hover colors

### PR DESCRIPTION
**Pull request by drbyte**
Ref discussion with @dennisns7d at https://github.com/lat9/ZCA-Bootstrap-Template/pull/19#issuecomment-751839000

### CODE REVIEW

**Comment by drbyte** [comment]
Argh ... I think I mixed up the colors. LOL

**Comment by drbyte** [comment]
I simplified it to just update the descriptions. The default colors appear to be fine.

Maybe this isn't even needed at all?

**Comment by lat9** [comment]
That change will only apply to a 'fresh' installation of the Bootstrap Template.  Was that your intent?

**Comment by drbyte** [comment]
> That change will only apply to a 'fresh' installation of the Bootstrap Template. Was that your intent?

Yes. Changing the wording simply adds clarity. No functionality is changed here.

**Comment by drbyte** [comment]
I considered version-stamping this file, but given that this change is almost cosmetic I opted not to.

Again, maybe this isn't even needed at all. I'm fine if you wish to close it without merging.

**Pull request merged**
